### ISSUE TITLE
Immutable types

### ISSUE THREAD

**Issue by ArtemKaRv** [JTOne123/liqpay-dotnet#1]
Hello,
Do you know how strings working in C# language?
Why you didn't use StringBuilder class in this method?
https://github.com/JTOne123/liqpay-dotnet/blob/71fea9370b94b15a1b0cc54627d97a049550fa25/LiqPaySDK/LiqPay.SDK/LiqPayClient.cs#L100

https://blog.ndepend.com/c-sharp-immutable-types-understanding-attraction/

**Comment by JTOne123** [comment]
Hello Artem, thank you for your comment!
It will be so helpful if you make a pull request.
